name: Dependabot Validation

permissions:
  contents: read

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  dependabot-check:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/jod

      - name: Install Dependencies
        run: npm ci

      - name: Check Files
        run: npm run check

      - name: Run Tests
        run: npm test
